services:
  goaccess-debug:
    container_name: goaccess
    command: >
      -m debugpy --listen 0.0.0.0:5678 /app/app.py --external-url=https://goaccess.papaya.local  --debug --loglevel debug
    build:
      context: .
      args:
        debbuger: true
    image: goaccess-debug
    restart: always
    ports:
      - "3050:3050"
      - "5678:5678"
    volumes:
      - data:/app/data
      - /var/geodb/:/app/geodb:ro
volumes:
  data:
    driver: local
